version: '2.3'

services:

  master:
    image: nginx:alpine
    #build: ./
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  web1:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./web1.html://usr/share/nginx/html/index.html

  web2:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./web2.html://usr/share/nginx/html/index.html

  web3:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./web3.html://usr/share/nginx/html/index.html
