version: '2.3'

services:

  master:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./master/:/usr/share/nginx/html/

  web1:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./web1/:/usr/share/nginx/html/v1/

  web2:
    image: nginx:alpine
    ports:
      - "80"
    volumes:
      - ./web2/:/usr/share/nginx/html/v2/

